name: Update Theme
description: "Update an existing plugin"
labels: update-theme

body:
  - type: markdown
    attributes:
      value: |
        Please enter your plugin CSS and certify that it meets the following requirements.

  - type: checkboxes
    attributes:
      label: Licensing & Certification
      options:
        - label: "I certify that I am releasing the CSS under the [CC0 1.0 Universal](https://creativecommons.org/publicdomain/zero/1.0/deed.en) license."
        - label: "I certify that the CSS provided actually works and is tested."
        - label: "I understand that the information provided, including the CSS, may be edited at any time without notice by a maintainer."

  - type: input
    attributes:
      label: "Item Name"
      description: "What item are you updating?"
      placeholder: "Item Name"

  - type: input
    attributes:
      label: "CSS Data URL"
      description: "Please provide your CSS as a Data URL."
      placeholder: "data:text/css;base64,..."

  - type: markdown
    attributes:
      value: |
        We'll verify that your theme follows the rules and that you own the theme. We can easily do that by looking up who created the initial issue and checking it against your account here.
